# Generated by Django 2.2.6 on 2019-10-17 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogRatingIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=False, to='core.Blog')),
                ('rating', models.ForeignKey(on_delete=False, to='core.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='BlogGalleryIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=100)),
                ('blog', models.ForeignKey(on_delete=False, to='core.Blog')),
                ('gallery', models.ForeignKey(on_delete=False, to='core.Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='gallery',
            field=models.ManyToManyField(through='core.BlogGalleryIntermediate', to='core.Gallery'),
        ),
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.ManyToManyField(through='core.BlogRatingIntermediate', to='core.Rating'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
