# Generated by Django 2.2.6 on 2019-10-22 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20191022_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogratingintermediate',
            name='blog',
            field=models.ForeignKey(on_delete=True, to='core.Blog'),
        ),
        migrations.AlterField(
            model_name='blogratingintermediate',
            name='rating',
            field=models.ForeignKey(on_delete=True, to='core.Rating'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogLikeIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=True, to='core.Blog')),
                ('like', models.ForeignKey(on_delete=True, to='core.Like')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(through='core.BlogLikeIntermediate', to='core.Like'),
        ),
    ]
