# Generated by Django 2.2.6 on 2019-12-13 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_videocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloglikeintermediate',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Blog'),
        ),
        migrations.AlterField(
            model_name='bloglikeintermediate',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Like'),
        ),
        migrations.AlterField(
            model_name='blogratingintermediate',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Blog'),
        ),
        migrations.AlterField(
            model_name='blogratingintermediate',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rating'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
