# Generated by Django 2.2.6 on 2020-01-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymentcustomer_paymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcustomer',
            name='customer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='order_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_signature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='plan_id',
            field=models.CharField(max_length=200),
        ),
    ]
