# Generated by Django 2.2.6 on 2020-02-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paymentdetail_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
