# Generated by Django 2.2.6 on 2019-11-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=123, max_length=14),
            preserve_default=False,
        ),
    ]
